[package]
name = "textty"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.40"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
scraper = "0.23.1"
serde = { version = "1.0.216", features = ["derive"] }
serde-aux = "4.5.0"
thiserror = "2.0.9"
ureq = { version = "3.0.8", features = ["json"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
