name: Release Build

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  release:
    name: Release for ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            artifact: textty
            name: textty-linux-amd64

          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            artifact: textty.exe
            name: textty-windows-amd64.exe

          - target: x86_64-apple-darwin
            runner: macos-latest
            artifact: textty
            name: textty-macos-amd64

          - target: aarch64-apple-darwin
            runner: macos-latest
            artifact: textty
            name: textty-macos-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --locked --release --target ${{ matrix.target }}

      - name: Upload artifact to workflow run
        uses: actions/upload-artifact@v4
        with:
          path: target/${{ matrix.target }}/release/${{ matrix.artifact }}
          name: ${{ matrix.name }}
          retention-days: 5

      - name: Rename binary
        run: |
          cd target/${{ matrix.target }}/release
          mv ${{ matrix.artifact }} ${{ matrix.name }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.name }}
