name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions:
  contents: write

jobs:
  release:
    name: Release for ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - prefix: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: textty

          - prefix: windows-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: textty.exe

          - prefix: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
            artifact: textty

          - prefix: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            artifact: textty

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --locked --release --target ${{ matrix.target }}

      - name: Upload artifact to workflow run
        uses: actions/upload-artifact@v4
        with:
          path: target/${{ matrix.target }}/release/${{ matrix.artifact }}
          name: ${{ matrix.prefix }}-${{ matrix.artifact }}
          retention-days: 5

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/${{ matrix.target }}/release/${{ matrix.artifact }}
          asset_name: ${{ matrix.prefix }}-${{ matrix.artifact }}
          draft: true
